var vodusBuild = "20200424-1-LIVE";

//LIVE API
//(function (v, o, d, u, s, a, m) { v['VodusObject'] = s; v[s] = v[s] || function () { (v[s].q = v[s].q || []).push(arguments) }, v[s].l = 1 * new Date(); v['vodus']['build'] = vodusBuild; v['vodus']['partner_code'] = vodus["partner_code"]; v['vodus']['interval'] = vodus["interval"]; v['vodus']['language'] = vodus["language"]; v['vodus']['modalClosable'] = vodus["modalClosable"]; v['vodus']['questionModalDelay'] = vodus["delay"]; v['vodus']['ctcTimer'] = vodus["ctc-timer"]; v['vodus']['ctcInterval'] = vodus["ctc-interval"]; v['vodus']['minSessionCount'] = vodus["minSessionCount"]; v['vodus']['noDemo'] = vodus["noDemo"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['dailyAllowance'] = vodus["dailyAllowance"]; v['vodus']['notificationPosition'] = vodus["notificationPosition"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['demographicCCType'] = vodus["demographic-cc-type"]; v['vodus']['demographicCTCTimer'] = vodus["demographic-ctc-timer"]; v['vodus']['demographicInterval'] = vodus["demographic-interval"]; v['vodus']['dmpUrl'] = vodus["dmp-url"]; v['vodus']['dmpType'] = vodus["dmp-type"]; v['vodus']['dmpCode'] = vodus["dmp-code"]; v['vodus']['dmpTarget'] = vodus["dmp-target"]; v['vodus']['catfishPosition'] = vodus["catfish-position"]; v['vodus']['ccPageScrollTrigger'] = vodus["cc-scroll-trigger"]; v['vodus']['bannerMode'] = vodus["banner-mode"]; v['vodus']['intervalBannerMode'] = vodus["interval-banner-mode"]; v['vodus']['env'] = "live"; a = o.createElement(d), m = o.getElementsByTagName(d)[0]; a.async = 1; a.src = u; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'https://voduscdn.azureedge.net/cc/scripts/vodus-main.min.js?buildId=' + vodusBuild, 'vodus');

//LIVE
//(function (v, o, d, u, s, a, m) { v['VodusObject'] = s; v[s] = v[s] || function () { (v[s].q = v[s].q || []).push(arguments) }, v[s].l = 1 * new Date(); v['vodus']['build'] = vodusBuild; v['vodus']['partner_code'] = vodus["partner_code"]; v['vodus']['interval'] = vodus["interval"]; v['vodus']['language'] = vodus["language"]; v['vodus']['modalClosable'] = vodus["modalClosable"]; v['vodus']['questionModalDelay'] = vodus["delay"]; v['vodus']['ctcTimer'] = vodus["ctc-timer"]; v['vodus']['ctcInterval'] = vodus["ctc-interval"]; v['vodus']['minSessionCount'] = vodus["minSessionCount"]; v['vodus']['noDemo'] = vodus["noDemo"];v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['dailyAllowance'] = vodus["dailyAllowance"]; v['vodus']['notificationPosition'] = vodus["notificationPosition"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['demographicCCType'] = vodus["demographic-cc-type"]; v['vodus']['demographicCTCTimer'] = vodus["demographic-ctc-timer"]; v['vodus']['demographicInterval'] = vodus["demographic-interval"]; v['vodus']['dmpUrl'] = vodus["dmp-url"]; v['vodus']['dmpType'] = vodus["dmp-type"]; v['vodus']['dmpCode'] = vodus["dmp-code"]; v['vodus']['dmpTarget'] = vodus["dmp-target"];a = o.createElement(d), m = o.getElementsByTagName(d)[0]; a.async = 1; a.src = u; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'https://vodus.com/scripts/app/vodus-main.js?buildId=' + vodusBuild, 'vodus');

//UAT
//(function (v, o, d, u, s, a, m) { v['VodusObject'] = s; v[s] = v[s] || function () { (v[s].q = v[s].q || []).push(arguments) }, v[s].l = 1 * new Date(); v['vodus']['build'] = vodusBuild; v['vodus']['partner_code'] = vodus["partner_code"]; v['vodus']['interval'] = vodus["interval"]; v['vodus']['language'] = vodus["language"]; v['vodus']['modalClosable'] = vodus["modalClosable"]; v['vodus']['questionModalDelay'] = vodus["delay"]; v['vodus']['ctcTimer'] = vodus["ctc-timer"]; v['vodus']['ctcInterval'] = vodus["ctc-interval"]; v['vodus']['minSessionCount'] = vodus["minSessionCount"]; v['vodus']['noDemo'] = vodus["noDemo"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['dailyAllowance'] = vodus["dailyAllowance"]; v['vodus']['notificationPosition'] = vodus["notificationPosition"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['demographicCCType'] = vodus["demographic-cc-type"]; v['vodus']['demographicCTCTimer'] = vodus["demographic-ctc-timer"]; v['vodus']['demographicInterval'] = vodus["demographic-interval"]; v['vodus']['dmpUrl'] = vodus["dmp-url"]; v['vodus']['dmpType'] = vodus["dmp-type"]; v['vodus']['dmpCode'] = vodus["dmp-code"]; v['vodus']['dmpTarget'] = vodus["dmp-target"]; v['vodus']['catfishPosition'] = vodus["catfish-position"]; v['vodus']['ccPageScrollTrigger'] = vodus["cc-scroll-trigger"]; v['vodus']['bannerMode'] = vodus["banner-mode"]; v['vodus']['intervalBannerMode'] = vodus["interval-banner-mode"]; v['vodus']['env'] = "uat"; a = o.createElement(d), m = o.getElementsByTagName(d)[0]; a.async = 1; a.src = u; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'https://vodus-api-uat.azurewebsites.net/scripts/app/vodus-main.js?buildId=' + vodusBuild, 'vodus');

//Local
//(function (v, o, d, u, s, a, m) { v['VodusObject'] = s; v[s] = v[s] || function () { (v[s].q = v[s].q || []).push(arguments) }, v[s].l = 1 * new Date(); v['vodus']['build'] = vodusBuild; v['vodus']['partner_code'] = vodus["partner_code"]; v['vodus']['interval'] = vodus["interval"]; v['vodus']['language'] = vodus["language"]; v['vodus']['modalClosable'] = vodus["modalClosable"]; v['vodus']['questionModalDelay'] = vodus["delay"]; v['vodus']['ctcTimer'] = vodus["ctc-timer"]; v['vodus']['ctcInterval'] = vodus["ctc-interval"]; v['vodus']['minSessionCount'] = vodus["minSessionCount"]; v['vodus']['noDemo'] = vodus["noDemo"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['dailyAllowance'] = vodus["dailyAllowance"]; v['vodus']['notificationPosition'] = vodus["notificationPosition"]; v['vodus']['ccType'] = vodus["ccType"]; v['vodus']['demographicCCType'] = vodus["demographic-cc-type"]; v['vodus']['demographicCTCTimer'] = vodus["demographic-ctc-timer"]; v['vodus']['demographicInterval'] = vodus["demographic-interval"]; v['vodus']['dmpUrl'] = vodus["dmp-url"]; v['vodus']['dmpType'] = vodus["dmp-type"]; v['vodus']['dmpCode'] = vodus["dmp-code"]; v['vodus']['dmpTarget'] = vodus["dmp-target"]; a = o.createElement(d), m = o.getElementsByTagName(d)[0]; a.async = 1; a.src = u; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'http://localhost:50889/cc/scripts/vodus-main.js?buildId=' + vodusBuild, 'vodus');
